vich_uploader:
    db_driver: orm

    mappings:
        media_photo:
            uri_prefix: /photo
            upload_destination: '%kernel.project_dir%/public/photo'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options: {date_time_format: 'Y/m/d'}
